# 系统模型模块
from .user import (
    SysUserQueryParams,
    SysUserCreate,
    SysUserUpdate,
    SysUserPasswordUpdate,
    SysUserSimpleResponse,
    SysRoleSimpleResponseForUser,
    SysUserResponseData,
    SysUserBatchUpdateStatus,
)
from .role import (
    SysRoleQueryParams,
    SysRoleCreate,
    SysRoleUpdate,
    SysRoleSimpleResponse,
    SysRoleResponseData,
    SysRoleBatchUpdateStatus,
)
from .menu import (
    SysMenuQueryParams,
    SysMenuCreate,
    SysMenuUpdate,
    SysMenuSimpleResponse,
    SysMenuTreeResponse,
    SysMenuResponseData,
    SysMenuBatchUpdateStatus,
)
from .dict import (
    SysDictQueryParams,
    SysDictCreate,
    SysDictUpdate,
    SysDictSimpleResponse,
    SysDictResponseData,
    SysDictItemQueryParams,
    SysDictItemCreate,
    SysDictItemUpdate,
    SysDictItemSimpleResponse,
    SysDictItemResponseData,
    SysDictWithItemsResponse,
    SysDictBatchUpdateStatus,
    SysDictItemBatchUpdateStatus,
)
from .config import (
    SysConfigQueryParams,
    SysConfigCreate,
    SysConfigUpdate,
    SysConfigBatchUpdate,
    SysConfigSimpleResponse,
    SysConfigResponseData,
    SysConfigReset,
    SysConfigByGroupQuery,
)

__all__ = [
    # 用户相关
    "SysUserQueryParams",
    "SysUserCreate",
    "SysUserUpdate",
    "SysUserPasswordUpdate",
    "SysUserSimpleResponse",
    "SysRoleSimpleResponseForUser",
    "SysUserResponseData",
    "SysUserBatchUpdateStatus",
    # 角色相关
    "SysRoleQueryParams",
    "SysRoleCreate",
    "SysRoleUpdate",
    "SysRoleSimpleResponse",
    "SysRoleResponseData",
    "SysRoleBatchUpdateStatus",
    # 菜单相关
    "SysMenuQueryParams",
    "SysMenuCreate",
    "SysMenuUpdate",
    "SysMenuSimpleResponse",
    "SysMenuTreeResponse",
    "SysMenuResponseData",
    "SysMenuBatchUpdateStatus",
    # 字典相关
    "SysDictQueryParams",
    "SysDictCreate",
    "SysDictUpdate",
    "SysDictSimpleResponse",
    "SysDictResponseData",
    "SysDictItemQueryParams",
    "SysDictItemCreate",
    "SysDictItemUpdate",
    "SysDictItemSimpleResponse",
    "SysDictItemResponseData",
    "SysDictWithItemsResponse",
    "SysDictBatchUpdateStatus",
    "SysDictItemBatchUpdateStatus",
    # 配置相关
    "SysConfigQueryParams",
    "SysConfigCreate",
    "SysConfigUpdate",
    "SysConfigBatchUpdate",
    "SysConfigSimpleResponse",
    "SysConfigResponseData",
    "SysConfigReset",
    "SysConfigByGroupQuery",
]
