"""update role-descript to desc

Revision ID: 0054cba63294
Revises: 063fa99615d6
Create Date: 2026-02-21 20:58:25.177105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0054cba63294'
down_revision: Union[str, Sequence[str], None] = '063fa99615d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sys_role', sa.Column('desc', sa.Text(), nullable=True, comment='角色描述'))
    op.drop_column('sys_role', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sys_role', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True, comment='角色描述'))
    op.drop_column('sys_role', 'desc')
    # ### end Alembic commands ###
