"""install scheduler plugin

Revision ID: 1f9e83e1daa6
Revises: 31ccb9a25342
Create Date: 2026-06-03 22:11:45.188722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1f9e83e1daa6'
down_revision: Union[str, Sequence[str], None] = '31ccb9a25342'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sys_scheduled_task',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='雪花算法主键 ID'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='任务名称'),
    sa.Column('task_key', sa.String(length=200), nullable=False, comment='任务唯一标识'),
    sa.Column('cron_expression', sa.String(length=100), nullable=False, comment='Cron 表达式'),
    sa.Column('description', sa.String(length=500), nullable=True, comment='任务描述'),
    sa.Column('trigger_type', sa.String(length=20), nullable=False, comment='触发类型: cron/interval/date'),
    sa.Column('trigger_params', sa.Text(), nullable=True, comment='触发参数 JSON'),
    sa.Column('status', sa.Boolean(), nullable=False, comment='状态: True启用/False禁用'),
    sa.Column('module', sa.String(length=100), nullable=True, comment='来源模块'),
    sa.Column('function_path', sa.String(length=200), nullable=True, comment='函数路径'),
    sa.Column('is_system', sa.Boolean(), nullable=False, comment='系统任务不可删除'),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True, comment='上次执行时间'),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True, comment='下次执行时间'),
    sa.Column('last_status', sa.String(length=20), nullable=True, comment='上次执行状态: success/failed/running'),
    sa.Column('timeout', sa.Integer(), nullable=False, comment='超时时间(秒)'),
    sa.Column('max_retries', sa.Integer(), nullable=False, comment='最大重试次数'),
    sa.Column('concurrent_policy', sa.String(length=20), nullable=False, comment='并发策略: skip/replace/run'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='删除时间，为空则未删除'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='定时任务表'
    )
    op.create_index(op.f('ix_sys_scheduled_task_id'), 'sys_scheduled_task', ['id'], unique=True)
    op.create_index(op.f('ix_sys_scheduled_task_task_key'), 'sys_scheduled_task', ['task_key'], unique=True)
    op.create_table('sys_scheduled_task_log',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='雪花算法主键 ID'),
    sa.Column('task_id', sa.BigInteger(), nullable=False, comment='任务ID'),
    sa.Column('task_name', sa.String(length=100), nullable=False, comment='任务名称(冗余)'),
    sa.Column('task_key', sa.String(length=200), nullable=False, comment='任务标识(冗余)'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态: running/success/failed/timeout'),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True, comment='开始时间'),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True, comment='结束时间'),
    sa.Column('duration_ms', sa.Float(), nullable=True, comment='耗时(毫秒)'),
    sa.Column('result', sa.Text(), nullable=True, comment='执行结果'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='错误信息'),
    sa.Column('retry_count', sa.Integer(), nullable=False, comment='重试次数'),
    sa.Column('triggered_by', sa.String(length=20), nullable=False, comment='触发方式: scheduler/manual'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='删除时间，为空则未删除'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='定时任务执行日志表'
    )
    op.create_index(op.f('ix_sys_scheduled_task_log_id'), 'sys_scheduled_task_log', ['id'], unique=True)
    op.create_index(op.f('ix_sys_scheduled_task_log_task_id'), 'sys_scheduled_task_log', ['task_id'], unique=False)
    op.drop_index(op.f('ix_plugin_registry_id'), table_name='plugin_registry')
    op.drop_index(op.f('ix_plugin_registry_name'), table_name='plugin_registry')
    op.drop_table('plugin_registry')
    op.drop_table('sys_user_tenant')
    op.drop_index(op.f('ix_sys_tenant_code'), table_name='sys_tenant')
    op.drop_index(op.f('ix_sys_tenant_id'), table_name='sys_tenant')
    op.drop_table('sys_tenant')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sys_tenant',
    sa.Column('id', sa.BIGINT(), autoincrement=False, nullable=False, comment='雪花算法主键 ID'),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False, comment='租户名称'),
    sa.Column('code', sa.VARCHAR(length=50), autoincrement=False, nullable=False, comment='租户编码'),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True, comment='租户描述'),
    sa.Column('status', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False, comment='状态：True-启用，False-禁用'),
    sa.Column('config', sa.TEXT(), autoincrement=False, nullable=True, comment='租户配置(JSON)'),
    sa.Column('contact_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True, comment='联系人'),
    sa.Column('contact_email', sa.VARCHAR(length=100), autoincrement=False, nullable=True, comment='联系邮箱'),
    sa.Column('contact_phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True, comment='联系手机'),
    sa.Column('max_users', sa.INTEGER(), server_default=sa.text('100'), autoincrement=False, nullable=False, comment='最大用户数'),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True, comment='删除时间，为空则未删除'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False, comment='创建时间'),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id', name='tenant_pkey'),
    sa.UniqueConstraint('name', name='tenant_name_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    comment='\n    租户表\n    存储租户/组织的基本信息和配置\n    ',
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_sys_tenant_id'), 'sys_tenant', ['id'], unique=True)
    op.create_index(op.f('ix_sys_tenant_code'), 'sys_tenant', ['code'], unique=True)
    op.create_table('sys_user_tenant',
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False, comment='用户ID'),
    sa.Column('tenant_id', sa.BIGINT(), autoincrement=False, nullable=False, comment='租户ID'),
    sa.Column('role', sa.VARCHAR(length=50), server_default=sa.text("'member'::character varying"), autoincrement=False, nullable=False, comment='租户角色：owner, admin, member'),
    sa.ForeignKeyConstraint(['tenant_id'], ['sys_tenant.id'], name=op.f('sys_user_tenant_tenant_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['sys_user.id'], name=op.f('sys_user_tenant_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'tenant_id', name=op.f('sys_user_tenant_pkey')),
    comment='用户租户关联表'
    )
    op.create_table('plugin_registry',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False, comment='雪花算法主键 ID'),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False, comment='插件名称'),
    sa.Column('version', sa.VARCHAR(length=50), autoincrement=False, nullable=False, comment='插件版本'),
    sa.Column('is_installed', sa.BOOLEAN(), autoincrement=False, nullable=False, comment='是否已安装'),
    sa.Column('installed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False, comment='安装时间'),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True, comment='删除时间，为空则未删除'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False, comment='创建时间'),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id', name=op.f('plugin_registry_pkey')),
    comment='\n    插件注册表\n    记录已安装的插件及其版本\n    '
    )
    op.create_index(op.f('ix_plugin_registry_name'), 'plugin_registry', ['name'], unique=True)
    op.create_index(op.f('ix_plugin_registry_id'), 'plugin_registry', ['id'], unique=True)
    op.drop_index(op.f('ix_sys_scheduled_task_log_task_id'), table_name='sys_scheduled_task_log')
    op.drop_index(op.f('ix_sys_scheduled_task_log_id'), table_name='sys_scheduled_task_log')
    op.drop_table('sys_scheduled_task_log')
    op.drop_index(op.f('ix_sys_scheduled_task_task_key'), table_name='sys_scheduled_task')
    op.drop_index(op.f('ix_sys_scheduled_task_id'), table_name='sys_scheduled_task')
    op.drop_table('sys_scheduled_task')
    # ### end Alembic commands ###
