"""Initial migration

Revision ID: 31d65bbf84bb
Revises: 
Create Date: 2026-02-02 09:56:55.572281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31d65bbf84bb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_user',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='雪花算法主键 ID'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='用户名'),
    sa.Column('phone_code', sa.String(length=10), nullable=False, comment='手机号区号，如：+86、+1 等'),
    sa.Column('phone', sa.String(length=13), nullable=False, comment='手机号'),
    sa.Column('salt', sa.String(length=255), nullable=True, comment='密码盐值'),
    sa.Column('password', sa.String(length=255), nullable=True, comment='密码哈希值'),
    sa.Column('email', sa.String(length=255), nullable=True, comment='邮箱'),
    sa.Column('wx_openid', sa.String(length=255), nullable=True, comment='微信 openid'),
    sa.Column('wx_unionid', sa.String(length=255), nullable=True, comment='微信 unionid'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='删除时间，为空则未删除'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='\n    用户表 - 存储用户信息\n    '
    )
    op.create_index(op.f('ix_app_user_id'), 'app_user', ['id'], unique=True)
    op.create_table('sys_config',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='雪花算法主键 ID'),
    sa.Column('key', sa.String(length=100), nullable=False, comment='配置键名'),
    sa.Column('value', sa.String(length=255), nullable=False, comment='配置值'),
    sa.Column('default_value', sa.String(length=255), nullable=True, comment='默认值'),
    sa.Column('validation_rule', sa.String(length=255), nullable=True, comment='校验规则'),
    sa.Column('description', sa.String(length=255), nullable=True, comment='配置描述'),
    sa.Column('type', sa.Enum('STRING', 'NUMBER', 'BOOLEAN', 'JSON', 'ARRAY', name='configtype'), nullable=False, comment='配置类型'),
    sa.Column('group', sa.Enum('SYSTEM', 'SECURITY', 'LOG', 'NETWORK', 'STORAGE', 'CUSTOM', name='configgroup'), nullable=False, comment='配置分组'),
    sa.Column('editable', sa.Boolean(), nullable=False, comment='是否可编辑'),
    sa.Column('is_system', sa.Boolean(), nullable=False, comment='是否为系统内置配置'),
    sa.Column('required', sa.Boolean(), nullable=False, comment='是否必填'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='删除时间，为空则未删除'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='\n    系统配置表\n    存储系统全局配置参数\n    '
    )
    op.create_index(op.f('ix_sys_config_id'), 'sys_config', ['id'], unique=True)
    op.create_index(op.f('ix_sys_config_key'), 'sys_config', ['key'], unique=True)
    op.create_table('sys_dict',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='雪花算法主键 ID'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='字典名称'),
    sa.Column('code', sa.String(length=100), nullable=False, comment='字典编码'),
    sa.Column('description', sa.Text(), nullable=True, comment='字典描述'),
    sa.Column('status', sa.Boolean(), nullable=False, comment='状态：True-启用，False-禁用'),
    sa.Column('is_system', sa.Boolean(), nullable=False, comment='是否为系统内置字典'),
    sa.Column('sort', sa.Integer(), nullable=False, comment='排序号'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='删除时间，为空则未删除'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='\n    系统字典表\n    存储字典分类信息\n    '
    )
    op.create_index(op.f('ix_sys_dict_code'), 'sys_dict', ['code'], unique=True)
    op.create_index(op.f('ix_sys_dict_id'), 'sys_dict', ['id'], unique=True)
    op.create_table('sys_menu',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='雪花算法主键 ID'),
    sa.Column('parent_id', sa.BigInteger(), nullable=True, comment='父菜单ID，顶级菜单为0或NULL'),
    sa.Column('icon', sa.String(length=50), nullable=True, comment='菜单图标'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='菜单名称'),
    sa.Column('path', sa.String(length=255), nullable=True, comment='路由路径'),
    sa.Column('component', sa.String(length=255), nullable=True, comment='组件路径'),
    sa.Column('redirect', sa.String(length=255), nullable=True, comment='重定向路径'),
    sa.Column('permission', sa.String(length=100), nullable=True, comment='权限标识，如 sys:user:list'),
    sa.Column('meta_title', sa.String(length=100), nullable=True, comment='路由标题'),
    sa.Column('meta_icon', sa.String(length=50), nullable=True, comment='路由图标'),
    sa.Column('meta_hidden', sa.Boolean(), nullable=False, comment='是否隐藏菜单'),
    sa.Column('meta_affix', sa.Boolean(), nullable=False, comment='是否固定标签'),
    sa.Column('meta_breadcrumb', sa.Boolean(), nullable=False, comment='是否显示面包屑'),
    sa.Column('status', sa.Boolean(), nullable=False, comment='状态：True-启用，False-禁用'),
    sa.Column('type', sa.Enum('CATALOG', 'MENU', 'BUTTON', 'EXTERNAL', name='menutype'), nullable=False, comment='菜单类型：catalog-目录, menu-菜单, button-按钮, external-外部链接'),
    sa.Column('sort', sa.Integer(), nullable=False, comment='排序号'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='删除时间，为空则未删除'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['parent_id'], ['sys_menu.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='\n    系统菜单表\n    存储系统菜单、目录和按钮等权限点\n    '
    )
    op.create_index(op.f('ix_sys_menu_id'), 'sys_menu', ['id'], unique=True)
    op.create_table('sys_permission',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='雪花算法主键 ID'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='权限名称'),
    sa.Column('code', sa.String(length=100), nullable=False, comment='权限编码（唯一标识符）'),
    sa.Column('description', sa.Text(), nullable=True, comment='权限描述'),
    sa.Column('resource_path', sa.String(length=255), nullable=True, comment='资源路径（如API路径、菜单URL等）'),
    sa.Column('method', sa.String(length=10), nullable=True, comment='请求方法（如GET, POST, PUT, DELETE等）'),
    sa.Column('category', sa.String(length=50), nullable=True, comment='权限分类'),
    sa.Column('type', sa.String(length=20), nullable=False, comment='权限类型：api, menu, button, data等'),
    sa.Column('status', sa.Boolean(), nullable=False, comment='状态：True-启用，False-禁用'),
    sa.Column('sort', sa.Integer(), nullable=False, comment='排序号'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='删除时间，为空则未删除'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='\n    系统权限表\n    存储细粒度的权限点，用于精确的权限控制\n    '
    )
    op.create_index(op.f('ix_sys_permission_code'), 'sys_permission', ['code'], unique=True)
    op.create_index(op.f('ix_sys_permission_id'), 'sys_permission', ['id'], unique=True)
    op.create_table('sys_role',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='雪花算法主键 ID'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='角色名称'),
    sa.Column('code', sa.String(length=100), nullable=False, comment='角色编码'),
    sa.Column('description', sa.Text(), nullable=True, comment='角色描述'),
    sa.Column('status', sa.Boolean(), nullable=False, comment='状态：True-启用，False-禁用'),
    sa.Column('is_default', sa.Boolean(), nullable=False, comment='是否为默认角色'),
    sa.Column('is_system', sa.Boolean(), nullable=False, comment='是否为系统内置角色'),
    sa.Column('sort', sa.Integer(), nullable=False, comment='排序号'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='删除时间，为空则未删除'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    comment='\n    系统角色表\n    存储角色信息及其关联的权限配置\n    '
    )
    op.create_index(op.f('ix_sys_role_code'), 'sys_role', ['code'], unique=True)
    op.create_index(op.f('ix_sys_role_id'), 'sys_role', ['id'], unique=True)
    op.create_table('sys_user',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='雪花算法主键 ID'),
    sa.Column('username', sa.String(length=50), nullable=False, comment='用户名'),
    sa.Column('password', sa.String(length=255), nullable=False, comment='密码（加密存储）'),
    sa.Column('nickname', sa.String(length=100), nullable=True, comment='用户昵称'),
    sa.Column('email', sa.String(length=100), nullable=True, comment='邮箱'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='手机号'),
    sa.Column('avatar', sa.Text(), nullable=True, comment='头像URL'),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=False, comment='最后登录时间'),
    sa.Column('last_login_ip', sa.String(length=50), nullable=False, comment='最后登录IP'),
    sa.Column('status', sa.Boolean(), nullable=False, comment='状态：True-启用，False-禁用'),
    sa.Column('is_superuser', sa.Boolean(), nullable=False, comment='是否为超级管理员'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='删除时间，为空则未删除'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone'),
    comment='\n    系统用户表\n    存储系统管理用户的基本信息和认证凭证\n    '
    )
    op.create_index(op.f('ix_sys_user_id'), 'sys_user', ['id'], unique=True)
    op.create_index(op.f('ix_sys_user_username'), 'sys_user', ['username'], unique=True)
    op.create_table('sys_dict_item',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='雪花算法主键 ID'),
    sa.Column('dict_id', sa.BigInteger(), nullable=False, comment='关联字典ID，字典删除时级联删除'),
    sa.Column('value', sa.String(length=100), nullable=False, comment='字典项值'),
    sa.Column('label', sa.String(length=100), nullable=False, comment='字典项文本'),
    sa.Column('description', sa.Text(), nullable=True, comment='字典项描述'),
    sa.Column('ext_info', sa.Text(), nullable=True, comment='扩展信息(JSON格式)'),
    sa.Column('status', sa.Boolean(), nullable=False, comment='状态：True-启用，False-禁用'),
    sa.Column('sort', sa.Integer(), nullable=False, comment='排序号'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='删除时间，为空则未删除'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['dict_id'], ['sys_dict.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='\n    系统字典数据表\n    存储字典的具体数据项\n    '
    )
    op.create_index(op.f('ix_sys_dict_item_id'), 'sys_dict_item', ['id'], unique=True)
    op.create_table('sys_role_menu',
    sa.Column('role_id', sa.BigInteger(), nullable=False, comment='角色ID'),
    sa.Column('menu_id', sa.BigInteger(), nullable=False, comment='菜单ID'),
    sa.Column('permission', sa.String(length=255), nullable=False, comment='权限类型：read, write, delete等'),
    sa.ForeignKeyConstraint(['menu_id'], ['sys_menu.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['sys_role.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'menu_id'),
    comment='角色菜单关联表'
    )
    op.create_table('sys_user_role',
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='用户ID'),
    sa.Column('role_id', sa.BigInteger(), nullable=False, comment='角色ID'),
    sa.ForeignKeyConstraint(['role_id'], ['sys_role.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['sys_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id'),
    comment='用户角色关联表'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sys_user_role')
    op.drop_table('sys_role_menu')
    op.drop_index(op.f('ix_sys_dict_item_id'), table_name='sys_dict_item')
    op.drop_table('sys_dict_item')
    op.drop_index(op.f('ix_sys_user_username'), table_name='sys_user')
    op.drop_index(op.f('ix_sys_user_id'), table_name='sys_user')
    op.drop_table('sys_user')
    op.drop_index(op.f('ix_sys_role_id'), table_name='sys_role')
    op.drop_index(op.f('ix_sys_role_code'), table_name='sys_role')
    op.drop_table('sys_role')
    op.drop_index(op.f('ix_sys_permission_id'), table_name='sys_permission')
    op.drop_index(op.f('ix_sys_permission_code'), table_name='sys_permission')
    op.drop_table('sys_permission')
    op.drop_index(op.f('ix_sys_menu_id'), table_name='sys_menu')
    op.drop_table('sys_menu')
    op.drop_index(op.f('ix_sys_dict_id'), table_name='sys_dict')
    op.drop_index(op.f('ix_sys_dict_code'), table_name='sys_dict')
    op.drop_table('sys_dict')
    op.drop_index(op.f('ix_sys_config_key'), table_name='sys_config')
    op.drop_index(op.f('ix_sys_config_id'), table_name='sys_config')
    op.drop_table('sys_config')
    op.drop_index(op.f('ix_app_user_id'), table_name='app_user')
    op.drop_table('app_user')
    # ### end Alembic commands ###
