"""add_operation_log_table

Revision ID: 374cbaf336b5
Revises: a1b2c3d4e5f6
Create Date: 2026-05-20 10:06:17.671553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '374cbaf336b5'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sys_operation_log',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='雪花算法主键 ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='操作人ID'),
    sa.Column('username', sa.String(length=50), nullable=False, comment='操作人用户名'),
    sa.Column('module', sa.String(length=50), nullable=False, comment='操作模块'),
    sa.Column('action', sa.String(length=50), nullable=False, comment='操作类型'),
    sa.Column('description', sa.String(length=255), nullable=True, comment='操作描述'),
    sa.Column('method', sa.String(length=10), nullable=True, comment='HTTP方法'),
    sa.Column('path', sa.String(length=255), nullable=True, comment='请求路径'),
    sa.Column('ip', sa.String(length=50), nullable=True, comment='客户端IP'),
    sa.Column('request_params', sa.Text(), nullable=True, comment='请求参数'),
    sa.Column('response_code', sa.Integer(), nullable=True, comment='响应状态码'),
    sa.Column('elapsed_ms', sa.Float(), nullable=True, comment='耗时(毫秒)'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='删除时间，为空则未删除'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='\n    系统操作日志表\n    记录用户的关键业务操作\n    '
    )
    op.create_index(op.f('ix_sys_operation_log_id'), 'sys_operation_log', ['id'], unique=True)
    op.create_index(op.f('ix_sys_operation_log_user_id'), 'sys_operation_log', ['user_id'], unique=False)
    op.alter_column('sys_user', 'password',
               existing_type=sa.VARCHAR(length=255),
               comment='密码（bcrypt加密存储）',
               existing_comment='密码（加密存储）',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sys_user', 'password',
               existing_type=sa.VARCHAR(length=255),
               comment='密码（加密存储）',
               existing_comment='密码（bcrypt加密存储）',
               existing_nullable=False)
    op.drop_index(op.f('ix_sys_operation_log_user_id'), table_name='sys_operation_log')
    op.drop_index(op.f('ix_sys_operation_log_id'), table_name='sys_operation_log')
    op.drop_table('sys_operation_log')
    # ### end Alembic commands ###
