"""remove scheduler plugin

Revision ID: 4597d6a8fe78
Revises: 1f9e83e1daa6
Create Date: 2026-06-03 22:29:38.121255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4597d6a8fe78'
down_revision: Union[str, Sequence[str], None] = '1f9e83e1daa6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('plugin_registry', 'id',
               existing_type=sa.BIGINT(),
               comment='雪花算法主键 ID',
               existing_nullable=False)
    op.alter_column('plugin_registry', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment='插件名称',
               existing_nullable=False)
    op.alter_column('plugin_registry', 'version',
               existing_type=sa.VARCHAR(length=50),
               comment='插件版本',
               existing_nullable=False)
    op.alter_column('plugin_registry', 'is_installed',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               comment='是否已安装',
               existing_server_default=sa.text('true'))
    op.alter_column('plugin_registry', 'installed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               comment='安装时间')
    op.alter_column('plugin_registry', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='删除时间，为空则未删除',
               existing_nullable=True)
    op.alter_column('plugin_registry', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               comment='创建时间')
    op.alter_column('plugin_registry', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='更新时间',
               existing_nullable=True)
    op.drop_constraint(op.f('plugin_registry_name_key'), 'plugin_registry', type_='unique')
    op.create_index(op.f('ix_plugin_registry_id'), 'plugin_registry', ['id'], unique=True)
    op.create_index(op.f('ix_plugin_registry_name'), 'plugin_registry', ['name'], unique=True)
    op.create_table_comment(
        'plugin_registry',
        '\n    插件注册表\n    记录已安装的插件及其版本\n    ',
        existing_comment=None,
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table_comment(
        'plugin_registry',
        existing_comment='\n    插件注册表\n    记录已安装的插件及其版本\n    ',
        schema=None
    )
    op.drop_index(op.f('ix_plugin_registry_name'), table_name='plugin_registry')
    op.drop_index(op.f('ix_plugin_registry_id'), table_name='plugin_registry')
    op.create_unique_constraint(op.f('plugin_registry_name_key'), 'plugin_registry', ['name'], postgresql_nulls_not_distinct=False)
    op.alter_column('plugin_registry', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=True)
    op.alter_column('plugin_registry', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               comment=None,
               existing_comment='创建时间')
    op.alter_column('plugin_registry', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='删除时间，为空则未删除',
               existing_nullable=True)
    op.alter_column('plugin_registry', 'installed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               comment=None,
               existing_comment='安装时间')
    op.alter_column('plugin_registry', 'is_installed',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               comment=None,
               existing_comment='是否已安装',
               existing_server_default=sa.text('true'))
    op.alter_column('plugin_registry', 'version',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='插件版本',
               existing_nullable=False)
    op.alter_column('plugin_registry', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='插件名称',
               existing_nullable=False)
    op.alter_column('plugin_registry', 'id',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='雪花算法主键 ID',
               existing_nullable=False)
    # ### end Alembic commands ###
