"""remove multi_tenant plugin

Revision ID: 4659f1a93c90
Revises: a737127368bd
Create Date: 2026-06-01 12:52:00.203663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4659f1a93c90'
down_revision: Union[str, Sequence[str], None] = 'a737127368bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_user', 'tenant_id')
    op.drop_column('sys_config', 'tenant_id')
    op.drop_column('sys_dict', 'tenant_id')
    op.drop_column('sys_dict_item', 'tenant_id')
    op.drop_column('sys_file', 'tenant_id')
    op.drop_column('sys_login_log', 'tenant_id')
    op.drop_column('sys_menu', 'tenant_id')
    op.drop_column('sys_notice', 'tenant_id')
    op.drop_column('sys_operation_log', 'tenant_id')
    op.drop_column('sys_role', 'tenant_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sys_role', sa.Column('tenant_id', sa.BIGINT(), autoincrement=False, nullable=True, comment='租户ID'))
    op.add_column('sys_operation_log', sa.Column('tenant_id', sa.BIGINT(), autoincrement=False, nullable=True, comment='租户ID'))
    op.add_column('sys_notice', sa.Column('tenant_id', sa.BIGINT(), autoincrement=False, nullable=True, comment='租户ID'))
    op.add_column('sys_menu', sa.Column('tenant_id', sa.BIGINT(), autoincrement=False, nullable=True, comment='租户ID'))
    op.add_column('sys_login_log', sa.Column('tenant_id', sa.BIGINT(), autoincrement=False, nullable=True, comment='租户ID'))
    op.add_column('sys_file', sa.Column('tenant_id', sa.BIGINT(), autoincrement=False, nullable=True, comment='租户ID'))
    op.add_column('sys_dict_item', sa.Column('tenant_id', sa.BIGINT(), autoincrement=False, nullable=True, comment='租户ID'))
    op.add_column('sys_dict', sa.Column('tenant_id', sa.BIGINT(), autoincrement=False, nullable=True, comment='租户ID'))
    op.add_column('sys_config', sa.Column('tenant_id', sa.BIGINT(), autoincrement=False, nullable=True, comment='租户ID'))
    op.add_column('app_user', sa.Column('tenant_id', sa.BIGINT(), autoincrement=False, nullable=True, comment='租户ID'))
    # ### end Alembic commands ###
