"""update user

Revision ID: 595b4f9bca68
Revises: 9a0589c7e855
Create Date: 2026-02-12 17:33:56.274235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '595b4f9bca68'
down_revision: Union[str, Sequence[str], None] = '9a0589c7e855'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sys_user', sa.Column('salt', sa.String(length=255), server_default='', nullable=False, comment='密码盐值'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sys_user', 'salt')
    # ### end Alembic commands ###
