"""install multi_tenant plugin

Revision ID: 76e0fc2dcf1a
Revises: ec20748d2885
Create Date: 2026-05-31 14:33:07.129870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '76e0fc2dcf1a'
down_revision: Union[str, Sequence[str], None] = 'ec20748d2885'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plugin_registry',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='雪花算法主键 ID'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='插件名称'),
    sa.Column('version', sa.String(length=50), nullable=False, comment='插件版本'),
    sa.Column('is_installed', sa.Boolean(), nullable=False, comment='是否已安装'),
    sa.Column('installed_at', sa.DateTime(timezone=True), nullable=False, comment='安装时间'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='删除时间，为空则未删除'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='\n    插件注册表\n    记录已安装的插件及其版本\n    '
    )
    op.create_index(op.f('ix_plugin_registry_id'), 'plugin_registry', ['id'], unique=True)
    op.create_index(op.f('ix_plugin_registry_name'), 'plugin_registry', ['name'], unique=True)
    op.add_column('app_user', sa.Column('tenant_id', sa.BigInteger(), nullable=True, comment='租户ID'))
    op.add_column('sys_config', sa.Column('tenant_id', sa.BigInteger(), nullable=True, comment='租户ID'))
    op.add_column('sys_dict', sa.Column('tenant_id', sa.BigInteger(), nullable=True, comment='租户ID'))
    op.add_column('sys_dict_item', sa.Column('tenant_id', sa.BigInteger(), nullable=True, comment='租户ID'))
    op.add_column('sys_file', sa.Column('tenant_id', sa.BigInteger(), nullable=True, comment='租户ID'))
    op.add_column('sys_role', sa.Column('tenant_id', sa.BigInteger(), nullable=True, comment='租户ID'))
    op.alter_column('sys_user_tenant', 'user_id',
               existing_type=sa.BIGINT(),
               comment='用户ID',
               existing_nullable=False)
    op.alter_column('sys_user_tenant', 'tenant_id',
               existing_type=sa.BIGINT(),
               comment='租户ID',
               existing_nullable=False)
    op.alter_column('sys_user_tenant', 'role',
               existing_type=sa.VARCHAR(length=50),
               comment='租户角色：owner, admin, member',
               existing_nullable=False,
               existing_server_default=sa.text("'member'::character varying"))
    op.create_table_comment(
        'sys_user_tenant',
        '用户租户关联表',
        existing_comment=None,
        schema=None
    )
    op.alter_column('tenant', 'id',
               existing_type=sa.BIGINT(),
               comment='雪花算法主键 ID',
               existing_nullable=False)
    op.alter_column('tenant', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment='租户名称',
               existing_nullable=False)
    op.alter_column('tenant', 'code',
               existing_type=sa.VARCHAR(length=50),
               comment='租户编码',
               existing_nullable=False)
    op.alter_column('tenant', 'description',
               existing_type=sa.TEXT(),
               comment='租户描述',
               existing_nullable=True)
    op.alter_column('tenant', 'status',
               existing_type=sa.BOOLEAN(),
               comment='状态：True-启用，False-禁用',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('tenant', 'config',
               existing_type=sa.TEXT(),
               comment='租户配置(JSON)',
               existing_nullable=True)
    op.alter_column('tenant', 'contact_name',
               existing_type=sa.VARCHAR(length=100),
               comment='联系人',
               existing_nullable=True)
    op.alter_column('tenant', 'contact_email',
               existing_type=sa.VARCHAR(length=100),
               comment='联系邮箱',
               existing_nullable=True)
    op.alter_column('tenant', 'contact_phone',
               existing_type=sa.VARCHAR(length=20),
               comment='联系手机',
               existing_nullable=True)
    op.alter_column('tenant', 'max_users',
               existing_type=sa.INTEGER(),
               comment='最大用户数',
               existing_nullable=False,
               existing_server_default=sa.text('100'))
    op.alter_column('tenant', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='删除时间，为空则未删除',
               existing_nullable=True)
    op.alter_column('tenant', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='创建时间',
               existing_nullable=False)
    op.alter_column('tenant', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='更新时间',
               existing_nullable=True)
    op.drop_constraint(op.f('tenant_code_key'), 'tenant', type_='unique')
    op.create_index(op.f('ix_tenant_code'), 'tenant', ['code'], unique=True)
    op.create_index(op.f('ix_tenant_id'), 'tenant', ['id'], unique=True)
    op.create_table_comment(
        'tenant',
        '\n    租户表\n    存储租户/组织的基本信息和配置\n    ',
        existing_comment=None,
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table_comment(
        'tenant',
        existing_comment='\n    租户表\n    存储租户/组织的基本信息和配置\n    ',
        schema=None
    )
    op.drop_index(op.f('ix_tenant_id'), table_name='tenant')
    op.drop_index(op.f('ix_tenant_code'), table_name='tenant')
    op.create_unique_constraint(op.f('tenant_code_key'), 'tenant', ['code'], postgresql_nulls_not_distinct=False)
    op.alter_column('tenant', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=True)
    op.alter_column('tenant', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('tenant', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='删除时间，为空则未删除',
               existing_nullable=True)
    op.alter_column('tenant', 'max_users',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='最大用户数',
               existing_nullable=False,
               existing_server_default=sa.text('100'))
    op.alter_column('tenant', 'contact_phone',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='联系手机',
               existing_nullable=True)
    op.alter_column('tenant', 'contact_email',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='联系邮箱',
               existing_nullable=True)
    op.alter_column('tenant', 'contact_name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='联系人',
               existing_nullable=True)
    op.alter_column('tenant', 'config',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='租户配置(JSON)',
               existing_nullable=True)
    op.alter_column('tenant', 'status',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='状态：True-启用，False-禁用',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('tenant', 'description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='租户描述',
               existing_nullable=True)
    op.alter_column('tenant', 'code',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='租户编码',
               existing_nullable=False)
    op.alter_column('tenant', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='租户名称',
               existing_nullable=False)
    op.alter_column('tenant', 'id',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='雪花算法主键 ID',
               existing_nullable=False)
    op.drop_table_comment(
        'sys_user_tenant',
        existing_comment='用户租户关联表',
        schema=None
    )
    op.alter_column('sys_user_tenant', 'role',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='租户角色：owner, admin, member',
               existing_nullable=False,
               existing_server_default=sa.text("'member'::character varying"))
    op.alter_column('sys_user_tenant', 'tenant_id',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='租户ID',
               existing_nullable=False)
    op.alter_column('sys_user_tenant', 'user_id',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='用户ID',
               existing_nullable=False)
    op.drop_column('sys_role', 'tenant_id')
    op.drop_column('sys_file', 'tenant_id')
    op.drop_column('sys_dict_item', 'tenant_id')
    op.drop_column('sys_dict', 'tenant_id')
    op.drop_column('sys_config', 'tenant_id')
    op.drop_column('app_user', 'tenant_id')
    op.drop_index(op.f('ix_plugin_registry_name'), table_name='plugin_registry')
    op.drop_index(op.f('ix_plugin_registry_id'), table_name='plugin_registry')
    op.drop_table('plugin_registry')
    # ### end Alembic commands ###
