"""remove email unique

Revision ID: 8898846e731e
Revises: 595b4f9bca68
Create Date: 2026-02-16 17:00:12.245569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8898846e731e'
down_revision: Union[str, Sequence[str], None] = '595b4f9bca68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('sys_user_email_key'), 'sys_user', type_='unique')
    op.drop_constraint(op.f('sys_user_phone_key'), 'sys_user', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('sys_user_phone_key'), 'sys_user', ['phone'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('sys_user_email_key'), 'sys_user', ['email'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
