"""install multi_tenant plugin

Revision ID: 99fe5c28d4be
Revises: g5b6c7d8e9f0
Create Date: 2026-05-31 12:38:28.897467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '99fe5c28d4be'
down_revision: Union[str, Sequence[str], None] = 'g5b6c7d8e9f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='雪花算法主键 ID'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='租户名称'),
    sa.Column('code', sa.String(length=50), nullable=False, comment='租户编码'),
    sa.Column('description', sa.Text(), nullable=True, comment='租户描述'),
    sa.Column('status', sa.Boolean(), nullable=False, comment='状态：True-启用，False-禁用'),
    sa.Column('config', sa.Text(), nullable=True, comment='租户配置(JSON)'),
    sa.Column('contact_name', sa.String(length=100), nullable=True, comment='联系人'),
    sa.Column('contact_email', sa.String(length=100), nullable=True, comment='联系邮箱'),
    sa.Column('contact_phone', sa.String(length=20), nullable=True, comment='联系手机'),
    sa.Column('max_users', sa.Integer(), nullable=False, comment='最大用户数'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='删除时间，为空则未删除'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    comment='\n    租户表\n    存储租户/组织的基本信息和配置\n    '
    )
    op.create_index(op.f('ix_tenant_code'), 'tenant', ['code'], unique=True)
    op.create_index(op.f('ix_tenant_id'), 'tenant', ['id'], unique=True)
    op.create_table('sys_user_tenant',
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='用户ID'),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False, comment='租户ID'),
    sa.Column('role', sa.String(length=50), nullable=False, comment='租户角色：owner, admin, member'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['sys_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'tenant_id'),
    comment='用户租户关联表'
    )
    op.add_column('app_user', sa.Column('tenant_id', sa.BigInteger(), nullable=True, comment='租户ID'))
    op.alter_column('plugin_registry', 'id',
               existing_type=sa.BIGINT(),
               comment='雪花算法主键 ID',
               existing_nullable=False)
    op.alter_column('plugin_registry', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment='插件名称',
               existing_nullable=False)
    op.alter_column('plugin_registry', 'version',
               existing_type=sa.VARCHAR(length=50),
               comment='插件版本',
               existing_nullable=False)
    op.alter_column('plugin_registry', 'is_installed',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               comment='是否已安装',
               existing_server_default=sa.text('true'))
    op.alter_column('plugin_registry', 'installed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               comment='安装时间')
    op.alter_column('plugin_registry', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='删除时间，为空则未删除',
               existing_nullable=True)
    op.alter_column('plugin_registry', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               comment='创建时间')
    op.alter_column('plugin_registry', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='更新时间',
               existing_nullable=True)
    op.drop_constraint(op.f('plugin_registry_name_key'), 'plugin_registry', type_='unique')
    op.create_index(op.f('ix_plugin_registry_id'), 'plugin_registry', ['id'], unique=True)
    op.create_index(op.f('ix_plugin_registry_name'), 'plugin_registry', ['name'], unique=True)
    op.create_table_comment(
        'plugin_registry',
        '\n    插件注册表\n    记录已安装的插件及其版本\n    ',
        existing_comment=None,
        schema=None
    )
    op.add_column('sys_config', sa.Column('tenant_id', sa.BigInteger(), nullable=True, comment='租户ID'))
    op.add_column('sys_dict', sa.Column('tenant_id', sa.BigInteger(), nullable=True, comment='租户ID'))
    op.add_column('sys_dict_item', sa.Column('tenant_id', sa.BigInteger(), nullable=True, comment='租户ID'))
    op.add_column('sys_file', sa.Column('tenant_id', sa.BigInteger(), nullable=True, comment='租户ID'))
    op.alter_column('sys_ip_blacklist', 'id',
               existing_type=sa.BIGINT(),
               comment='雪花算法主键 ID',
               existing_nullable=False)
    op.alter_column('sys_ip_blacklist', 'ip',
               existing_type=sa.VARCHAR(length=64),
               comment='IP 地址',
               existing_nullable=False)
    op.alter_column('sys_ip_blacklist', 'type',
               existing_type=sa.VARCHAR(length=16),
               comment='类型：permanent / temporary',
               existing_nullable=False)
    op.alter_column('sys_ip_blacklist', 'reason',
               existing_type=sa.VARCHAR(length=255),
               comment='加入原因',
               existing_nullable=True)
    op.alter_column('sys_ip_blacklist', 'expire_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='过期时间（temporary 必填）',
               existing_nullable=True)
    op.alter_column('sys_ip_blacklist', 'creator_id',
               existing_type=sa.BIGINT(),
               comment='创建人ID（系统自动写入时为空）',
               existing_nullable=True)
    op.alter_column('sys_ip_blacklist', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='删除时间，为空则未删除',
               existing_nullable=True)
    op.alter_column('sys_ip_blacklist', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('sys_ip_blacklist', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='更新时间',
               existing_nullable=True)
    op.drop_constraint(op.f('sys_ip_blacklist_ip_key'), 'sys_ip_blacklist', type_='unique')
    op.create_table_comment(
        'sys_ip_blacklist',
        '\n    IP 黑名单表\n    permanent: 永久；temporary: 临时（expire_at 为空表示永久）\n    ',
        existing_comment=None,
        schema=None
    )
    op.add_column('sys_role', sa.Column('tenant_id', sa.BigInteger(), nullable=True, comment='租户ID'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sys_role', 'tenant_id')
    op.drop_table_comment(
        'sys_ip_blacklist',
        existing_comment='\n    IP 黑名单表\n    permanent: 永久；temporary: 临时（expire_at 为空表示永久）\n    ',
        schema=None
    )
    op.create_unique_constraint(op.f('sys_ip_blacklist_ip_key'), 'sys_ip_blacklist', ['ip'], postgresql_nulls_not_distinct=False)
    op.alter_column('sys_ip_blacklist', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=True)
    op.alter_column('sys_ip_blacklist', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('sys_ip_blacklist', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='删除时间，为空则未删除',
               existing_nullable=True)
    op.alter_column('sys_ip_blacklist', 'creator_id',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='创建人ID（系统自动写入时为空）',
               existing_nullable=True)
    op.alter_column('sys_ip_blacklist', 'expire_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='过期时间（temporary 必填）',
               existing_nullable=True)
    op.alter_column('sys_ip_blacklist', 'reason',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='加入原因',
               existing_nullable=True)
    op.alter_column('sys_ip_blacklist', 'type',
               existing_type=sa.VARCHAR(length=16),
               comment=None,
               existing_comment='类型：permanent / temporary',
               existing_nullable=False)
    op.alter_column('sys_ip_blacklist', 'ip',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment='IP 地址',
               existing_nullable=False)
    op.alter_column('sys_ip_blacklist', 'id',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='雪花算法主键 ID',
               existing_nullable=False)
    op.drop_column('sys_file', 'tenant_id')
    op.drop_column('sys_dict_item', 'tenant_id')
    op.drop_column('sys_dict', 'tenant_id')
    op.drop_column('sys_config', 'tenant_id')
    op.drop_table_comment(
        'plugin_registry',
        existing_comment='\n    插件注册表\n    记录已安装的插件及其版本\n    ',
        schema=None
    )
    op.drop_index(op.f('ix_plugin_registry_name'), table_name='plugin_registry')
    op.drop_index(op.f('ix_plugin_registry_id'), table_name='plugin_registry')
    op.create_unique_constraint(op.f('plugin_registry_name_key'), 'plugin_registry', ['name'], postgresql_nulls_not_distinct=False)
    op.alter_column('plugin_registry', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=True)
    op.alter_column('plugin_registry', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               comment=None,
               existing_comment='创建时间')
    op.alter_column('plugin_registry', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='删除时间，为空则未删除',
               existing_nullable=True)
    op.alter_column('plugin_registry', 'installed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               comment=None,
               existing_comment='安装时间')
    op.alter_column('plugin_registry', 'is_installed',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               comment=None,
               existing_comment='是否已安装',
               existing_server_default=sa.text('true'))
    op.alter_column('plugin_registry', 'version',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='插件版本',
               existing_nullable=False)
    op.alter_column('plugin_registry', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='插件名称',
               existing_nullable=False)
    op.alter_column('plugin_registry', 'id',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='雪花算法主键 ID',
               existing_nullable=False)
    op.drop_column('app_user', 'tenant_id')
    op.drop_table('sys_user_tenant')
    op.drop_index(op.f('ix_tenant_id'), table_name='tenant')
    op.drop_index(op.f('ix_tenant_code'), table_name='tenant')
    op.drop_table('tenant')
    # ### end Alembic commands ###
