"""change_operation_log_user_id_to_bigint

Revision ID: a4ca5a267393
Revises: 5ef79f3941a4
Create Date: 2026-05-21 16:07:55.406629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4ca5a267393'
down_revision: Union[str, Sequence[str], None] = '5ef79f3941a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sys_operation_log', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_comment='操作人ID',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sys_operation_log', 'user_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_comment='操作人ID',
               existing_nullable=False)
    # ### end Alembic commands ###
