"""remove multi_tenant plugin

Revision ID: b713ee0de03e
Revises: 76e0fc2dcf1a
Create Date: 2026-05-31 23:04:51.925235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b713ee0de03e'
down_revision: Union[str, Sequence[str], None] = '76e0fc2dcf1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_user', 'tenant_id')
    op.drop_column('sys_config', 'tenant_id')
    op.drop_column('sys_dict', 'tenant_id')
    op.drop_column('sys_dict_item', 'tenant_id')
    op.drop_column('sys_file', 'tenant_id')
    op.drop_column('sys_role', 'tenant_id')
    op.drop_index(op.f('ix_tenant_code'), table_name='sys_tenant')
    op.drop_index(op.f('ix_tenant_id'), table_name='sys_tenant')
    op.create_index(op.f('ix_sys_tenant_code'), 'sys_tenant', ['code'], unique=True)
    op.create_index(op.f('ix_sys_tenant_id'), 'sys_tenant', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sys_tenant_id'), table_name='sys_tenant')
    op.drop_index(op.f('ix_sys_tenant_code'), table_name='sys_tenant')
    op.create_index(op.f('ix_tenant_id'), 'sys_tenant', ['id'], unique=True)
    op.create_index(op.f('ix_tenant_code'), 'sys_tenant', ['code'], unique=True)
    op.add_column('sys_role', sa.Column('tenant_id', sa.BIGINT(), autoincrement=False, nullable=True, comment='租户ID'))
    op.add_column('sys_file', sa.Column('tenant_id', sa.BIGINT(), autoincrement=False, nullable=True, comment='租户ID'))
    op.add_column('sys_dict_item', sa.Column('tenant_id', sa.BIGINT(), autoincrement=False, nullable=True, comment='租户ID'))
    op.add_column('sys_dict', sa.Column('tenant_id', sa.BIGINT(), autoincrement=False, nullable=True, comment='租户ID'))
    op.add_column('sys_config', sa.Column('tenant_id', sa.BIGINT(), autoincrement=False, nullable=True, comment='租户ID'))
    op.add_column('app_user', sa.Column('tenant_id', sa.BIGINT(), autoincrement=False, nullable=True, comment='租户ID'))
    # ### end Alembic commands ###
