"""update config

Revision ID: c2519d982254
Revises: 3bb7efe35943
Create Date: 2026-02-22 15:17:40.040215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2519d982254'
down_revision: Union[str, Sequence[str], None] = '3bb7efe35943'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sys_config', 'required')
    op.drop_column('sys_config', 'editable')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sys_config', sa.Column('editable', sa.BOOLEAN(), autoincrement=False, nullable=False, comment='是否可编辑'))
    op.add_column('sys_config', sa.Column('required', sa.BOOLEAN(), autoincrement=False, nullable=False, comment='是否必填'))
    # ### end Alembic commands ###
