"""update system user modules

Revision ID: d682e7fcf71a
Revises: 31d65bbf84bb
Create Date: 2026-02-12 10:23:24.532600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd682e7fcf71a'
down_revision: Union[str, Sequence[str], None] = '31d65bbf84bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sys_user', 'last_login_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_comment='最后登录时间')
    op.alter_column('sys_user', 'last_login_ip',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_comment='最后登录IP')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sys_user', 'last_login_ip',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_comment='最后登录IP')
    op.alter_column('sys_user', 'last_login_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_comment='最后登录时间')
    # ### end Alembic commands ###
