"""restore notice tables

Revision ID: ec20748d2885
Revises: f8cc24898343
Create Date: 2026-05-31 13:53:18.592241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ec20748d2885'
down_revision: Union[str, Sequence[str], None] = 'f8cc24898343'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sys_notice',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='雪花算法主键 ID'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='通知标题'),
    sa.Column('content', sa.Text(), nullable=False, comment='通知内容（支持HTML）'),
    sa.Column('sender_id', sa.BigInteger(), nullable=False, comment='发送者用户ID'),
    sa.Column('sender_name', sa.String(length=100), nullable=False, comment='发送者名称'),
    sa.Column('type', sa.String(length=50), nullable=False, comment='通知类型：announcement-公告, system-系统, operation-操作提醒, approval-审批通知'),
    sa.Column('target_type', sa.String(length=50), nullable=False, comment='推送范围：all-全员, role-按角色, user-按指定用户'),
    sa.Column('target_role_ids', postgresql.ARRAY(sa.BigInteger()), nullable=True, comment='目标角色ID列表（target_type=role时有效）'),
    sa.Column('target_user_ids', postgresql.ARRAY(sa.BigInteger()), nullable=True, comment='目标用户ID列表（target_type=user时有效）'),
    sa.Column('priority', sa.String(length=20), nullable=False, comment='优先级：low-低, normal-普通, high-高, urgent-紧急'),
    sa.Column('status', sa.Boolean(), nullable=False, comment='状态：True-已发布, False-草稿'),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True, comment='发布时间'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='删除时间，为空则未删除'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='\n    系统通知表\n    存储系统公告、操作提醒、审批通知等\n    '
    )
    op.create_index(op.f('ix_sys_notice_id'), 'sys_notice', ['id'], unique=True)
    op.create_table('sys_notice_read',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='雪花算法主键 ID'),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='用户ID'),
    sa.Column('notice_id', sa.BigInteger(), nullable=False, comment='通知ID'),
    sa.Column('is_read', sa.Boolean(), nullable=False, comment='是否已读'),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True, comment='阅读时间'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='删除时间，为空则未删除'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'notice_id', name='uix_user_notice'),
    comment='用户通知阅读记录表'
    )
    op.create_index(op.f('ix_sys_notice_read_id'), 'sys_notice_read', ['id'], unique=True)
    op.create_index(op.f('ix_sys_notice_read_notice_id'), 'sys_notice_read', ['notice_id'], unique=False)
    op.create_index(op.f('ix_sys_notice_read_user_id'), 'sys_notice_read', ['user_id'], unique=False)
    op.drop_table('sys_user_tenant')
    op.drop_index(op.f('ix_plugin_registry_id'), table_name='plugin_registry')
    op.drop_index(op.f('ix_plugin_registry_name'), table_name='plugin_registry')
    op.drop_table('plugin_registry')
    op.drop_index(op.f('ix_tenant_code'), table_name='tenant')
    op.drop_index(op.f('ix_tenant_id'), table_name='tenant')
    op.drop_table('tenant')
    op.drop_column('app_user', 'tenant_id')
    op.drop_column('sys_config', 'tenant_id')
    op.drop_column('sys_dict', 'tenant_id')
    op.drop_column('sys_dict_item', 'tenant_id')
    op.drop_column('sys_file', 'tenant_id')
    op.drop_column('sys_role', 'tenant_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sys_role', sa.Column('tenant_id', sa.BIGINT(), autoincrement=False, nullable=True, comment='租户ID'))
    op.add_column('sys_file', sa.Column('tenant_id', sa.BIGINT(), autoincrement=False, nullable=True, comment='租户ID'))
    op.add_column('sys_dict_item', sa.Column('tenant_id', sa.BIGINT(), autoincrement=False, nullable=True, comment='租户ID'))
    op.add_column('sys_dict', sa.Column('tenant_id', sa.BIGINT(), autoincrement=False, nullable=True, comment='租户ID'))
    op.add_column('sys_config', sa.Column('tenant_id', sa.BIGINT(), autoincrement=False, nullable=True, comment='租户ID'))
    op.add_column('app_user', sa.Column('tenant_id', sa.BIGINT(), autoincrement=False, nullable=True, comment='租户ID'))
    op.create_table('tenant',
    sa.Column('id', sa.BIGINT(), server_default=sa.text("nextval('tenant_id_seq'::regclass)"), autoincrement=True, nullable=False, comment='雪花算法主键 ID'),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False, comment='租户名称'),
    sa.Column('code', sa.VARCHAR(length=50), autoincrement=False, nullable=False, comment='租户编码'),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True, comment='租户描述'),
    sa.Column('status', sa.BOOLEAN(), autoincrement=False, nullable=False, comment='状态：True-启用，False-禁用'),
    sa.Column('config', sa.TEXT(), autoincrement=False, nullable=True, comment='租户配置(JSON)'),
    sa.Column('contact_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True, comment='联系人'),
    sa.Column('contact_email', sa.VARCHAR(length=100), autoincrement=False, nullable=True, comment='联系邮箱'),
    sa.Column('contact_phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True, comment='联系手机'),
    sa.Column('max_users', sa.INTEGER(), autoincrement=False, nullable=False, comment='最大用户数'),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True, comment='删除时间，为空则未删除'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False, comment='创建时间'),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id', name='tenant_pkey'),
    sa.UniqueConstraint('name', name='tenant_name_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    comment='\n    租户表\n    存储租户/组织的基本信息和配置\n    ',
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_tenant_id'), 'tenant', ['id'], unique=True)
    op.create_index(op.f('ix_tenant_code'), 'tenant', ['code'], unique=True)
    op.create_table('plugin_registry',
    sa.Column('id', sa.BIGINT(), autoincrement=False, nullable=False, comment='雪花算法主键 ID'),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False, comment='插件名称'),
    sa.Column('version', sa.VARCHAR(length=50), autoincrement=False, nullable=False, comment='插件版本'),
    sa.Column('is_installed', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False, comment='是否已安装'),
    sa.Column('installed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False, comment='安装时间'),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True, comment='删除时间，为空则未删除'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False, comment='创建时间'),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id', name=op.f('plugin_registry_pkey')),
    comment='\n    插件注册表\n    记录已安装的插件及其版本\n    '
    )
    op.create_index(op.f('ix_plugin_registry_name'), 'plugin_registry', ['name'], unique=True)
    op.create_index(op.f('ix_plugin_registry_id'), 'plugin_registry', ['id'], unique=True)
    op.create_table('sys_user_tenant',
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False, comment='用户ID'),
    sa.Column('tenant_id', sa.BIGINT(), autoincrement=False, nullable=False, comment='租户ID'),
    sa.Column('role', sa.VARCHAR(length=50), autoincrement=False, nullable=False, comment='租户角色：owner, admin, member'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('sys_user_tenant_tenant_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['sys_user.id'], name=op.f('sys_user_tenant_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'tenant_id', name=op.f('sys_user_tenant_pkey')),
    comment='用户租户关联表'
    )
    op.drop_index(op.f('ix_sys_notice_read_user_id'), table_name='sys_notice_read')
    op.drop_index(op.f('ix_sys_notice_read_notice_id'), table_name='sys_notice_read')
    op.drop_index(op.f('ix_sys_notice_read_id'), table_name='sys_notice_read')
    op.drop_table('sys_notice_read')
    op.drop_index(op.f('ix_sys_notice_id'), table_name='sys_notice')
    op.drop_table('sys_notice')
    # ### end Alembic commands ###
