"""install scheduler plugin

Revision ID: ed6be07ef320
Revises: 4597d6a8fe78
Create Date: 2026-06-03 22:29:44.369826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ed6be07ef320'
down_revision: Union[str, Sequence[str], None] = '4597d6a8fe78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_plugin_registry_id'), table_name='plugin_registry')
    op.drop_index(op.f('ix_plugin_registry_name'), table_name='plugin_registry')
    op.drop_table('plugin_registry')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plugin_registry',
    sa.Column('id', sa.BIGINT(), autoincrement=False, nullable=False, comment='雪花算法主键 ID'),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False, comment='插件名称'),
    sa.Column('version', sa.VARCHAR(length=50), autoincrement=False, nullable=False, comment='插件版本'),
    sa.Column('is_installed', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False, comment='是否已安装'),
    sa.Column('installed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False, comment='安装时间'),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True, comment='删除时间，为空则未删除'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False, comment='创建时间'),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id', name=op.f('plugin_registry_pkey')),
    comment='\n    插件注册表\n    记录已安装的插件及其版本\n    '
    )
    op.create_index(op.f('ix_plugin_registry_name'), 'plugin_registry', ['name'], unique=True)
    op.create_index(op.f('ix_plugin_registry_id'), 'plugin_registry', ['id'], unique=True)
    # ### end Alembic commands ###
