/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'demo',
    path: '/demo',
    component: 'layout.base',
    meta: {
      title: 'demo',
      i18nKey: 'route.demo',
      order: 5,
      localIcon: 'example'
    },
    children: [
      {
        name: 'demo_dict',
        path: '/demo/dict',
        component: 'view.demo_dict',
        meta: {
          title: 'demo_dict',
          i18nKey: 'route.demo_dict',
          localIcon: 'book-alphabet'
        }
      },
      {
        name: 'demo_upload',
        path: '/demo/upload',
        component: 'view.demo_upload',
        meta: {
          title: 'demo_upload',
          i18nKey: 'route.demo_upload',
          localIcon: 'upload'
        }
      }
    ]
  },
  {
    name: 'export-task',
    path: '/log/export-task',
    component: 'layout.base$view.export-task',
    meta: {
      title: 'export-task',
      i18nKey: 'route.export-task',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'face',
    path: '/face',
    component: 'layout.base$view.face',
    meta: {
      title: 'face',
      i18nKey: 'route.face'
    }
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      localIcon: 'monitor-dashboard',
      order: 1
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'log',
    path: '/log',
    component: 'layout.base',
    meta: {
      title: 'log',
      i18nKey: 'route.log',
      localIcon: 'file-document-outline',
      order: 3
    },
    children: [
      {
        name: 'log_login-log',
        path: '/log/login-log',
        component: 'view.log_login-log',
        meta: {
          title: 'log_login-log',
          i18nKey: 'route.log_login-log'
        }
      },
      {
        name: 'log_online-user',
        path: '/log/online-user',
        component: 'view.log_online-user',
        meta: {
          title: 'log_online-user',
          i18nKey: 'route.log_online-user'
        }
      },
      {
        name: 'log_operation-log',
        path: '/log/operation-log',
        component: 'view.log_operation-log',
        meta: {
          title: 'log_operation-log',
          i18nKey: 'route.log_operation-log'
        }
      },
      {
        name: 'log_robot-log',
        path: '/log/robot-log',
        component: 'view.log_robot-log',
        meta: {
          title: 'log_robot-log',
          i18nKey: 'route.log_robot-log'
        }
      }
    ]
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'manage',
    path: '/manage',
    component: 'layout.base',
    meta: {
      title: 'manage',
      i18nKey: 'route.manage'
    },
    children: [
      {
        name: 'manage_announcement',
        path: '/manage/announcement',
        component: 'view.manage_announcement',
        meta: {
          title: 'manage_announcement',
          i18nKey: 'route.manage_announcement'
        }
      },
      {
        name: 'manage_config',
        path: '/manage/config',
        component: 'view.manage_config',
        meta: {
          title: 'manage_config',
          i18nKey: 'route.manage_config'
        }
      },
      {
        name: 'manage_dict',
        path: '/manage/dict',
        component: 'view.manage_dict',
        meta: {
          title: 'manage_dict',
          i18nKey: 'route.manage_dict'
        }
      },
      {
        name: 'manage_file',
        path: '/manage/file',
        component: 'view.manage_file',
        meta: {
          title: 'manage_file',
          i18nKey: 'route.manage_file'
        }
      },
      {
        name: 'manage_ip-blacklist',
        path: '/manage/ip-blacklist',
        component: 'view.manage_ip-blacklist',
        meta: {
          title: 'manage_ip-blacklist',
          i18nKey: 'route.manage_ip-blacklist'
        }
      },
      {
        name: 'manage_menu',
        path: '/manage/menu',
        component: 'view.manage_menu',
        meta: {
          title: 'manage_menu',
          i18nKey: 'route.manage_menu'
        }
      },
      {
        name: 'manage_role',
        path: '/manage/role',
        component: 'view.manage_role',
        meta: {
          title: 'manage_role',
          i18nKey: 'route.manage_role'
        }
      },
      {
        name: 'manage_scheduler',
        path: '/manage/scheduler',
        component: 'view.manage_scheduler',
        meta: {
          title: 'manage_scheduler',
          i18nKey: 'route.manage_scheduler'
        }
      },
      {
        name: 'manage_scheduler-log',
        path: '/manage/scheduler-log',
        component: 'view.manage_scheduler-log',
        meta: {
          title: 'manage_scheduler-log',
          i18nKey: 'route.manage_scheduler-log'
        }
      },
      {
        name: 'manage_user',
        path: '/manage/user',
        component: 'view.manage_user',
        meta: {
          title: 'manage_user',
          i18nKey: 'route.manage_user'
        }
      }
    ]
  },
  {
    name: 'map-editor',
    path: '/map-editor',
    component: 'layout.base$view.map-editor',
    meta: {
      title: 'map-editor',
      i18nKey: 'route.map-editor'
    }
  },
  {
    name: 'monitor',
    path: '/monitor',
    component: 'layout.base$view.monitor',
    meta: {
      title: 'monitor',
      i18nKey: 'route.monitor',
      localIcon: 'chart-areaspline-variant',
      order: 4
    }
  },
  {
    name: 'open-merchant',
    path: '/open-merchant',
    component: 'layout.base',
    meta: {
      title: 'open-merchant',
      i18nKey: 'route.open-merchant'
    },
    children: [
      {
        name: 'open-merchant_call-log',
        path: '/open-merchant/call-log',
        component: 'view.open-merchant_call-log',
        meta: {
          title: 'open-merchant_call-log',
          i18nKey: 'route.open-merchant_call-log'
        }
      },
      {
        name: 'open-merchant_merchant',
        path: '/open-merchant/merchant',
        component: 'view.open-merchant_merchant',
        meta: {
          title: 'open-merchant_merchant',
          i18nKey: 'route.open-merchant_merchant'
        }
      }
    ]
  },
  {
    name: 'operation-monitor',
    path: '/operation-monitor',
    component: 'layout.base$view.operation-monitor',
    meta: {
      title: 'operation-monitor',
      i18nKey: 'route.operation-monitor'
    }
  },
  {
    name: 'robot',
    path: '/robot',
    component: 'layout.base',
    meta: {
      title: 'robot',
      i18nKey: 'route.robot'
    },
    children: [
      {
        name: 'robot_model',
        path: '/robot/model',
        component: 'view.robot_model',
        meta: {
          title: 'robot_model',
          i18nKey: 'route.robot_model'
        }
      }
    ]
  },
  {
    name: 'robots',
    path: '/robots',
    component: 'layout.base$view.robots',
    meta: {
      title: 'robots',
      i18nKey: 'route.robots'
    }
  },
  {
    name: 'scene',
    path: '/scene',
    component: 'layout.base',
    meta: {
      title: 'scene',
      i18nKey: 'route.scene'
    },
    children: [
      {
        name: 'scene_group',
        path: '/scene/group',
        component: 'view.scene_group',
        meta: {
          title: 'scene_group',
          i18nKey: 'route.scene_group'
        }
      },
      {
        name: 'scene_map',
        path: '/scene/map',
        component: 'view.scene_map',
        meta: {
          title: 'scene_map',
          i18nKey: 'route.scene_map'
        }
      }
    ]
  },
  {
    name: 'settings',
    path: '/settings',
    component: 'layout.base$view.settings',
    meta: {
      title: 'settings',
      i18nKey: 'route.settings',
      localIcon: 'cog'
    }
  },
  {
    name: 'task',
    path: '/task',
    component: 'layout.base$view.task',
    meta: {
      title: 'task',
      i18nKey: 'route.task'
    }
  }
];
